[package]
name = "rust_jni"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex-literal = "1.0.0"
jni = "0.21.1"
lazy_static = "1.5.0"
pbkdf2 = "0.12.2"
rand = "0.9.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
uuid = "1.15.1"
