services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  echoserver:
    image: vhiribarren/echo-server
    ports:
      - 4001:4001/udp
      - 5001:5001
  websocket:
    image: jmalloc/echo-server
    ports:
      - 2001:8080
  webserver_http:
    image: nginx:latest
    ports:
      - 80:80
      - 3001:80
    restart: always
    volumes:
      - ./nginx/conf_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf_http/:/etc/nginx/conf.d/:ro
      - ./nginx/html/:/etc/nginx/html/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  webserver_https:
    image: nginx:latest
    ports:
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf_https/:/etc/nginx/conf.d/:ro
      - ./nginx/html/:/etc/nginx/html/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  ctf_tcp:
    build: ./ctf_tcp
    ports:
      - 7001:7001
  ctf_websocket:
    build: ./ctf_websocket
    volumes:
      - ./certbot/conf:/app/certs:ro
    ports:
      - 6001:6001
  ctf_feedback:
    build: ./ctf_feedback
    volumes:
      - ./certbot/conf:/app/certs:ro
    ports:
      - 8008:8008
  ctf_anticheat:
    build: ./ctf_anticheat
    volumes:
      - ./certbot/conf:/app/certs:ro
      - ./ctf_anticheat/signature_keys:/app/signature_keys:ro
    ports:
      - 8001:8008